

name: Build and upload artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'

    - name: 'Build and package'
      run: |
        go install github.com/fyne-io/fyne-cross@latest
        fyne-cross darwin
        fyne-cross windows
        fyne-cross linux

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: goimgpack
        path: "fyne-cross/dist" 
